version: '3.12'
services:
  web:
    build: .
    image: accu:latest
    container_name: accu-back-app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=postgres-django
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432    
    volumes:
      - .:/app
    networks:
      - my-network
  db:   
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres-django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:


